# Generated by Django 2.2 on 2020-07-14 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_de_creation', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'sous categorie',
                'verbose_name_plural': 'sous categories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('disponible', models.BooleanField(default=True)),
                ('image', models.ImageField(default='images/photo.jpg', upload_to='images/')),
                ('quantite', models.IntegerField(default=1)),
                ('premier_prix', models.FloatField(default=0.0)),
                ('prix', models.FloatField()),
                ('taux_reduction', models.FloatField(null=True)),
                ('promotion', models.BooleanField(default=False)),
                ('etoile', models.IntegerField(default=0)),
                ('date_de_creation', models.DateField(auto_now_add=True)),
                ('sous_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.SousCategorie', verbose_name='Les sous categories')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ['-date_de_creation'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_de_creation', models.DateField(auto_now_add=True)),
                ('souscategorie', models.ManyToManyField(blank=True, to='boutique.SousCategorie')),
            ],
            options={
                'verbose_name': 'categorie',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
