# Generated by Django 2.2 on 2020-07-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
