# Generated by Django 2.2 on 2020-07-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_produit_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='taux_reduction',
            field=models.FloatField(blank=True, default=0, max_length=3),
        ),
    ]
