# Generated by Django 2.2 on 2020-07-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0006_auto_20200717_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='date_de_creation',
            field=models.DateField(auto_now_add=True, verbose_name='Ajouter le'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='etoile',
            field=models.IntegerField(default=0, verbose_name='Nombre de vue'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='produit',
            name='promotion',
            field=models.BooleanField(default=False, verbose_name='Mise en promotion'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite',
            field=models.IntegerField(default=1, verbose_name='quantité'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='taux_reduction',
            field=models.FloatField(blank=True, default=0, max_length=3, verbose_name='taux de réduction'),
        ),
    ]
