# Generated by Django 2.2 on 2020-07-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0008_compteuser_panier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='produits',
            field=models.ManyToManyField(blank=True, related_name='produits', to='boutique.Produit'),
        ),
    ]
