# Generated by Django 2.2 on 2020-07-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0010_auto_20200719_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
