# Generated by Django 2.2 on 2020-07-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0011_auto_20200719_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
    ]
