# Generated by Django 2.2 on 2020-07-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0012_auto_20200720_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='quantite',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='panier',
            name='produits',
            field=models.ManyToManyField(blank=True, null=True, related_name='produits', to='boutique.Produit'),
        ),
    ]
