# Generated by Django 2.2 on 2020-07-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0013_auto_20200721_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='nom',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='panier',
            name='produits',
            field=models.ManyToManyField(blank=True, related_name='produits', to='boutique.Produit'),
        ),
    ]
