# Generated by Django 2.2 on 2020-07-25 20:38

import boutique.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0014_auto_20200725_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to=boutique.models.renommage, verbose_name='Image plus')),
                ('sous_categorie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.SousCategorie')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='media',
            field=models.ManyToManyField(blank=True, to='boutique.Media'),
        ),
    ]
