# Generated by Django 2.2 on 2020-07-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0015_auto_20200725_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='prix',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
