# Generated by Django 2.2 on 2020-07-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0016_panier_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('corrige', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
