# Generated by Django 2.2 on 2020-07-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0017_bug'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='terminer',
            field=models.BooleanField(default=False, verbose_name='Terminé'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='date_de_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='prix',
            field=models.PositiveIntegerField(default=0, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='traite',
            field=models.BooleanField(default=False, verbose_name='Traité'),
        ),
    ]
