# Generated by Django 2.2 on 2020-07-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0018_auto_20200727_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'verbose_name': 'Rapport de bug', 'verbose_name_plural': 'Rapports de bug'},
        ),
        migrations.AlterModelOptions(
            name='souscategorie',
            options={'ordering': ['nom'], 'verbose_name': 'Sous Categorie', 'verbose_name_plural': 'Sous Categories'},
        ),
    ]
