# Generated by Django 2.2 on 2020-07-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0020_contact_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='adress',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
