# Generated by Django 2.2 on 2020-07-29 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0022_avisdemande_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='panier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.Panier'),
        ),
    ]
