# Generated by Django 2.2 on 2020-07-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0023_auto_20200729_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='valider',
            field=models.BooleanField(default=False),
        ),
    ]
