# Generated by Django 2.2 on 2020-07-29 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0024_commande_valider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.Contact'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.Produit'),
        ),
    ]
