# Generated by Django 2.2 on 2020-07-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0025_auto_20200729_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='method',
            field=models.CharField(choices=[('V', 'Visa'), ('P', 'PayPal'), ('L', 'Livraison')], default='L', help_text="Choix d'un mode de payement", max_length=1),
        ),
    ]
