# Generated by Django 2.2 on 2020-08-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0027_auto_20200804_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panieritem',
            name='prix_du_produit',
            field=models.FloatField(blank=True, default=0, verbose_name='Prix total du Poduit'),
        ),
    ]
