# Generated by Django 2.2 on 2020-08-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0032_auto_20200804_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='panieritem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proprio', to='boutique.CompteUser'),
        ),
        migrations.RemoveField(
            model_name='panieritem',
            name='produits',
        ),
        migrations.AddField(
            model_name='panieritem',
            name='produits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='boutique.Produit'),
        ),
    ]
