# Generated by Django 2.2 on 2020-08-04 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0033_auto_20200804_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panieritem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.CompteUser'),
        ),
    ]
