# Generated by Django 2.2 on 2020-08-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0034_auto_20200804_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panieritem',
            name='produits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.Produit'),
        ),
    ]
