# Generated by Django 2.2 on 2020-08-05 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0035_auto_20200804_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panieritem',
            options={'verbose_name': 'Panier intermediaire'},
        ),
    ]
