# Generated by Django 2.2 on 2020-08-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0036_auto_20200805_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='picture',
            field=models.URLField(default=''),
        ),
    ]
