# Generated by Django 2.2 on 2020-08-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0038_auto_20200820_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='picture',
            field=models.URLField(blank=True, default=''),
        ),
    ]
